version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
      # WARNING a utiliser en production, Cree un dossier a la racine du projet pour le mapper dans docker
      # - .node_modules:/app/node_modules

    depends_on:
      - mariadb
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER_API}
      DB_PASSWORD: ${DB_PASSWORD_API}
      DB_NAME: ${DB_NAME}
      PORT: ${PORT}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}

    command: nodemon --legacy-watch index.js

  mariadb:
    image: mariadb:latest
    build:
      context: .
      dockerfile: Dockerfile.mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER_API}
      MYSQL_PASSWORD: ${DB_PASSWORD_API}
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./queuebuddy.sql:/docker-entrypoint-initdb.d/queuebuddy.sql
    ports:
      - "3306:3306"

  adminer:
      image: adminer
      restart: always
      ports:
        - "8080:8080"

volumes:
  mariadb_data:
