FROM node:20-alpine

WORKDIR /home/node/app

COPY package*.json ./

RUN npm install

# WARNING à supprimer lors du déploiement en production
# Installer nodemon globalement pour faciliter le développement
RUN npm install -g nodemon 

# Crée un utilisateur afin de ne pas être en root
USER node 

# WARNING à mettre ne production
# COPY . .

# CMD ["npm", "start"]
CMD ["nodemon", "--legacy-watch", "index.js"]
